# Generated by Django 5.0.2 on 2024-02-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime', models.CharField(choices=[('THEFT', 'Theft'), ('MURDER', 'Murder'), ('KIDNAPPING', 'Kidnapping'), ('BURGLARY', 'Burglary'), ('TRAFFICKING', 'Trafficking'), ('BANDITRY', 'Banditry'), ('RAPE', 'Rape'), ('ROBBERY', 'Robbery'), ('EXAM_MALPRACTICE', 'Exam_Malpractice'), ('ASSAULT', 'Assault'), ('FRAUD', 'Fraud'), ('VANDALISM', 'Vandalism'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('crime_location', models.CharField(max_length=100)),
                ('image_evidence', models.ImageField(upload_to='crime_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
