# Generated by Django 5.0.2 on 2024-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousreport',
            name='crime',
            field=models.CharField(choices=[('THEFT', 'Theft'), ('MURDER', 'Murder'), ('KIDNAPPING', 'Kidnapping'), ('CYBERCRIME', 'Cybercrime'), ('BURGLARY', 'Burglary'), ('TRAFFICKING', 'Trafficking'), ('BANDITRY', 'Banditry'), ('MANSLAUGHTER', 'Manslaughter'), ('RAPE', 'Rape'), ('ROBBERY', 'Robbery'), ('EXAM_MALPRACTICE', 'Exam_Malpractice'), ('ASSAULT', 'Assault'), ('FRAUD', 'Fraud'), ('VANDALISM', 'Vandalism'), ('CHILD ABUSE', 'Child Abuse'), ('ARSON', 'Arson'), ('CULTISM', 'Cultism'), ('OTHERS', 'Others')], max_length=50),
        ),
    ]
