# Generated by Django 5.0.2 on 2024-02-27 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_anonymousreport_crime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime', models.CharField(choices=[('SELECT_CRIME', 'Select a crime'), ('THEFT', 'Theft'), ('MURDER', 'Murder'), ('KIDNAPPING', 'Kidnapping'), ('CYBERCRIME', 'Cybercrime'), ('BURGLARY', 'Burglary'), ('TRAFFICKING', 'Trafficking'), ('BANDITRY', 'Banditry'), ('MANSLAUGHTER', 'Manslaughter'), ('RAPE', 'Rape'), ('ROBBERY', 'Robbery'), ('EXAM_MALPRACTICE', 'Exam Malpractice'), ('ASSAULT', 'Assault'), ('FRAUD', 'Fraud'), ('VANDALISM', 'Vandalism'), ('CHILD ABUSE', 'Child Abuse'), ('ARSON', 'Arson'), ('CULTISM', 'Cultism'), ('OTHERS', 'Others')], default='SELECT_CRIME', max_length=50)),
                ('description', models.TextField()),
                ('crime_location', models.CharField(max_length=100)),
                ('image_evidence', models.ImageField(upload_to='crime_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
